services:
  langflow:
    image: langflowai/langflow:1.4.2
    container_name: langflow_app
    environment:  
      - LANGFLOW_AUTO_LOGIN=true
    ports:
      - "7860:7860"
    working_dir: /workspace
    volumes:
      - ./:/workspace
