services:
  # Servicio LangFlow
  langflow:
    image: langflowai/langflow:1.3.4
    container_name: langflow_app
    environment:
      # URL de conexión que LangFlow usará por defecto
      - LANGFLOW_DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydatabase
    ports:
      - "7860:7860"
    volumes:
      - ./:/workspace
    working_dir: /workspace
    depends_on:
      db:
        condition: service_healthy

  # Base de datos PostgreSQL
  db:
    image: postgres:15
    container_name: codespace_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: {}
